### ISSUE TITLE
orderBy 没有使用用例啊。不知道怎么用

### ISSUE THREAD

**Issue by timy-life** [huyanping/Zebra-PHP-ArrayGroupBy#1]

**Comment by huyanping** [comment]
example: $sorted = array_orderby($data, 'volume', SORT_DESC, 'edition', SORT_ASC);
源码中有注释的，$data参数为要orderby的数组，后面是不定长参数，一个列名，一个排序规则

**Comment by huyanping** [comment]
README.MD里添加了一个demo
