### ISSUE TITLE
php版本,要求多少啊?5.3.3不能用啊.能不能兼容一下啊??

### ISSUE THREAD

**Issue by timy-life** [huyanping/Zebra-PHP-ArrayGroupBy#2]
php版本,要求多少啊?5.3.3不能用啊.能不能兼容一下啊??

**Comment by huyanping** [comment]
语法不兼容，自己调整下就好了。目前这个包已经没有在维护了。

**Comment by timy-life** [comment]
大神,求教调整啊.

		$group_by_fields = [
		    'pay_reason' => function ($value) {
			    return $value;
		    }
		];

		$group_by_value = [
		    'pay_reason_name' => function ($value) {
			    return $value[0]['pay_reason_name'];
		    },
		    'total_price' => function ($value) {
			    return array_sum(array_column($value, 'total_price'));
		    },
		    'item_num' => function ($value) {
			    foreach ($value as $key => $val) {
				    if ($val['item_type'] == 28) {
					    $order_by_product[] = $val;
				    }
			    }
			    $count = $order_by_product ? array_sum(array_column($order_by_product, 'item_num')) : 0;
			    return $count;
		    },
		    'order_id' => [
			'callback' => function ($value) {
				return count($value);
			},
			'as' => 'buy_count'
		    ],
		    'buyer_id' => [
			'callback' => function ($value) {
				return count(array_unique(array_column($value, 'buyer_id')));
			},
			'as' => 'buyer_num'
		    ],
		    'unit_price' => function ($value) {
			    return $value[0]['unit_price'];
		    },
		];

		$group = new ArrayGroupBy($res);

**Comment by timy-life** [comment]
已经处理完毕.就是更换简写数组格式为,array()
